### ISSUE TITLE
Installation Issue #2

### ISSUE THREAD

**Issue by rtybanana** [NiftyPET/NiftyPET#3] opened 2020-11-18 03:38 UTC
An error occurred while attempting to install niftyPET on an HPC. I've extracted what I think is the important part of the error message out. I don't understand what this means. 

Is it attempting to prompt? Because a prompt did not appear at any point.

```python
    i> conda environment found: nipet
    i> using this CUDA architecture(s): -gencode=arch=compute_35,code=compute_35;
    i> conda environment found: nipet
    Folder for hardware mu-mapsTraceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Dedvau/nipet/setup.py", line 128, in <module>
        Cnt['HMUDIR'] = askdirectory(**prompt)
      File "/tmp/pip-install-Dedvau/nipet/setup.py", line 27, in askdirectory
        path = raw_input(title)
    EOFError: EOF when reading a line
    Cleaning up...
```

Any help will be greatly appreciated, thanks.

**Comment by pjmark** [comment] 2020-11-25 12:51
Hi Rory

Sorry for the late reply.  Which Python version are you using?  2 or 3?

Cheers,
Pawel

**Comment by rtybanana** [comment] 2020-11-25 14:00
Not to worry, I actually sorted this issue by instead downloading the source code for NIPET and NIMPA seperately and running the relevant setup.py scripts.

However, this particular issue with the recommended installation method still exists. I was using Python 2.7 if that helps.

**Comment by rtybanana** [comment] 2020-11-25 14:05
Also some other information that may be relevant.

Python 2.7 installed in an anaconda environment.
Attempting to install on an HPC running CentOS Linux release 7.6.1810

**Comment by pjmark** [comment] 2020-11-26 13:06
I have it working under Centos 7 and 8, so no problems there.

With the remote installation (no gui) it may be better to use Python 3.  If you can, try cloning it from github and then checking out branch dev2, which is version 2.0, and which soon will become the master branch for Python 3.

Let me know how it goes and if you can do it.

Cheers,
Pawel

**Comment by casperdcl** [comment] 2021-02-01 22:57
I think the error (hanging during install) may be due to waiting for user input regarding where to find hardware mumaps etc. Probably a duplicate of #1. Also probably best to use the latest Python3 version which has this fixed.

Let us know if Python 3 (e.g. https://github.com/NiftyPET/NIPET#quick-install) doesn't work.

**Closed** 2021-02-01 22:57 UTC
